# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  # Triggers the workflow on push or pull request events but only for the vuepress-blog branch
  push:
    branches: [ vuepress-blog ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install and Build
      run: yarn && yarn build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        REPOSITORY_NAME: jinmu333/jinmu333.github.io
        FOLDER: docs/.vuepress/dist
        BUILD_SCRIPT: yarn && yarn build

    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: jinmu333/jinmu333.github.io
        BRANCH: master # The branch the action should deploy to.
        FOLDER: docs/.vuepress/dist # The folder the action should deploy.
